Feature/add api base
Gh0stF1ghter/Rent-n-Ride-AdminPanelService pull request #9
Opened 2024-07-15 10:51 UTC by Gh0stF1ghter

2024-07-15 11:02 UTC, VadimZharikov approved these changes

2024-07-15 15:24 UTC, Vlada25 requested changes

2024-07-15 15:24 UTC, Vlada25 commented on AdminPanelService/AdminPanel.API/Exceptions/ExceptionResponse.cs
> +public record ExceptionResponse(int StatusCode, string message);
Why do you have different variable case here?

2024-07-15 15:51 UTC, Vlada25 approved these changes

2024-07-16 12:53 UTC, pavelGagarin0870 approved these changes

2024-07-16 12:57 UTC, merged